[package]
name = "p31"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["crates/*"]

[dependencies]
bevy = "*"
dolly = { path = "crates/dolly" }
tween = { path = "crates/tween" }
cameras = { path = "crates/cameras" }

[dev-dependencies]
bevy-inspector-egui = "0.18"
