[package]
name = "fps_controller"
version = "0.0.1"
edition = "2018"
description = ""
readme = "README.md"

[workspace]
resolver = "2"

[dependencies]
bevy = "0.10"
bevy_rapier3d = "0.21.0"
valve_maps = { path = "../valve_maps" }
egui_helper = { path = "../egui_helper" }
bevy-tnua = { version = "0.2", features = ["rapier_3d"] }

[dev-dependencies]
cameras = { path = "../cameras" }

[patch.crates-io]
bevy_rapier3d = { git = 'https://github.com/dimforge/bevy_rapier' }